[project]
name = "pdf-cutter"
version = "1.0.0"
description = "Print massive documents at school by splitting them into 30-page chunks"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pypdf>=5.4.0"]
